version: "3.8"

services:
  bot:
    build:
      context: .
    image: bot
    restart: always
    environment:
      - DISCORD_TOKEN = MTMyMTgzNDI4NzExNjMyMDgzOA.G0F6U7.mfTzYHAAjCuqKyaIHltNgHaCis5UoqxFldDrbw
      - CHANNEL_ID = 1312171714272297065
